### ISSUE TITLE
It doesn't count trains

### ISSUE THREAD

**Issue by mlgkorte** [charliejh/CSGORouletteSimulator#1]
Hi!

I tried your simulator but it only shows these : 
('Total Spins:', 100000)
('Dice:', 6634, '\nCT:', 46615, '\nT:', 46751)
('Results:', ['T', 'T', 'CT', 'T', 'T', 'Dice', 'T', ............

It doesn't show the "trains" and the money you require.

Please check it.

**Comment by charliejh** [comment]
Hi mlgkorte,

I am running the Python code in JetBrains PyCharm and it appears to be working fine. I re-tested it using IDLE (Python Shell) and it appears to crash when the number of spins is set to a high value. Could you let me know what software you are using to run the code and if the program crashes? Could you possibly try lowering the number of spins (lets say to 1000) and see if you get the same result?

Thanks.

**Comment by charliejh** [comment]
No response. Closing this issue.
